/**
 * Performance Verification Tests
 *
 * Usage:
 *   npx vitest run __tests__/perf-verification.test.ts
 *
 * These are pass/fail assertions that validate optimization claims.
 * Run after each optimization to confirm the target was met.
 *
 * This file reads from perf-results/ JSON files generated by the
 * perf scripts. It does NOT run the benchmarks itself — that way
 * you can run benchmarks once and test the results multiple times.
 */

import { describe, it, expect, beforeAll } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(__dirname, "..");
const RESULTS_DIR = path.join(ROOT, "perf-results");

function loadJSON(filename: string) {
  const filepath = path.join(RESULTS_DIR, filename);
  if (!existsSync(filepath)) return null;
  return JSON.parse(readFileSync(filepath, "utf8"));
}

function loadBaselineJSON(filename: string) {
  const filepath = path.join(RESULTS_DIR, "baseline", filename);
  if (!existsSync(filepath)) return null;
  return JSON.parse(readFileSync(filepath, "utf8"));
}

// ============================================================
// Optimization 1: Bundle Size (GeoJSON RSC + cities.ts split)
// ============================================================
describe("Bundle Optimization", () => {
  let bundle: any;

  beforeAll(() => {
    bundle = loadJSON("bundle-sizes.json");
  });

  it("bundle analysis was run (bundle-sizes.json exists)", () => {
    expect(bundle).not.toBeNull();
  });

  it("china-geo.json is NOT in client JS bundles", () => {
    if (!bundle) return; // skip if no data
    expect(bundle.geoJsonInClientBundle).toBe(false);
  });

  it("full cities data is NOT in client JS bundles", () => {
    if (!bundle) return;
    expect(bundle.fullCitiesInClientBundle).toBe(false);
  });

  it("total JS (gzip) is reduced by at least 100KB compared to baseline", () => {
    const baseline = loadBaselineJSON("bundle-sizes.json");
    if (!bundle || !baseline) return; // skip if data missing
    const reduction = baseline.jsGzipBytes - bundle.jsGzipBytes;
    expect(reduction).toBeGreaterThan(100 * 1024); // 100KB minimum
  });

  it("total JS (gzip) is under 500KB", () => {
    if (!bundle) return;
    expect(bundle.jsGzipBytes).toBeLessThan(500 * 1024);
  });
});

// ============================================================
// Optimization 2: CSS (globals.css 810 lines -> ~30 lines)
// ============================================================
describe("CSS Optimization", () => {
  let css: any;

  beforeAll(() => {
    css = loadJSON("css-metrics.json");
  });

  it("CSS metrics were run (css-metrics.json exists)", () => {
    expect(css).not.toBeNull();
  });

  it("globals.css is under 60 lines (target ~30)", () => {
    if (!css) return;
    expect(css.sourceGlobalsCSS.lines).toBeLessThan(60);
  });

  it("globals.css raw size is under 3KB", () => {
    if (!css) return;
    expect(css.sourceGlobalsCSS.rawBytes).toBeLessThan(3 * 1024);
  });

  it("CSS modules exist (migration from globals to modules)", () => {
    if (!css) return;
    // At least some CSS module files should exist if migration happened
    // This is a weak check — the real check is that globals.css is smaller
    expect(css.sourceCSSFiles.length).toBeGreaterThan(0);
  });
});

// ============================================================
// Optimization 3: Storage (mutex + atomic writes)
// ============================================================
describe("Storage Optimization", () => {
  let storage: any;

  beforeAll(() => {
    storage = loadJSON("storage-benchmark.json");
  });

  it("storage benchmark was run (storage-benchmark.json exists)", () => {
    expect(storage).not.toBeNull();
  });

  it("single write P50 is under 10ms", () => {
    if (!storage) return;
    expect(storage.singleWrite.p50).toBeLessThan(10);
  });

  it("single write P99 is under 50ms", () => {
    if (!storage) return;
    expect(storage.singleWrite.p99).toBeLessThan(50);
  });

  it("concurrent writes do not corrupt data", () => {
    if (!storage) return;
    expect(storage.concurrentWrites.corruptedReads).toBe(0);
  });

  it("atomic write P50 is under 15ms", () => {
    if (!storage) return;
    expect(storage.atomicWrite.p50).toBeLessThan(15);
  });

  it("large payload (500 memories) P95 is under 100ms", () => {
    if (!storage) return;
    expect(storage.largePayload.p95).toBeLessThan(100);
  });
});

// ============================================================
// Optimization 4: Architecture (ProvinceMap / MemoryTools split)
// ============================================================
describe("Architecture Optimization (Source Metrics)", () => {
  let source: any;

  beforeAll(() => {
    source = loadJSON("source-metrics.json");
  });

  it("source metrics were run (source-metrics.json exists)", () => {
    expect(source).not.toBeNull();
  });

  it("ProvinceMap is split into 3+ files, each under 800 lines", () => {
    if (!source) return;
    expect(source.provinceMap.fileCount).toBeGreaterThanOrEqual(3);
    for (const file of source.provinceMap.files) {
      expect(file.lines).toBeLessThan(800);
    }
  });

  it("MemoryTools is split into 4+ files, each under 500 lines", () => {
    if (!source) return;
    expect(source.memoryTools.fileCount).toBeGreaterThanOrEqual(4);
    for (const file of source.memoryTools.files) {
      expect(file.lines).toBeLessThan(500);
    }
  });

  it("cities-index.ts exists (split from cities.ts)", () => {
    if (!source) return;
    expect(source.citiesIndexTS.exists).toBe(true);
    expect(source.citiesIndexTS.bytes).toBeLessThan(20 * 1024); // < 20KB
  });

  it("china-geo.json is 582KB (unchanged on disk, but should not be in client bundle)", () => {
    if (!source) return;
    // The file exists for RSC to use, but must not be bundled to client
    expect(source.chinaGeoJSON.KB).toBeGreaterThan(500);
  });
});

// ============================================================
// API Latency
// ============================================================
describe("API Performance", () => {
  let api: any;

  beforeAll(() => {
    api = loadJSON("api-benchmark.json");
  });

  it("API benchmark was run (api-benchmark.json exists)", () => {
    expect(api).not.toBeNull();
  });

  it("GET /api/memories P95 < 200ms", () => {
    if (!api) return;
    const ep = api.endpoints.find((e: any) => e.url === "/api/memories" && e.method === "GET");
    expect(ep).toBeDefined();
    expect(ep.latency.p95).toBeLessThan(200);
  });

  it("POST /api/auth/login P95 < 200ms", () => {
    if (!api) return;
    const ep = api.endpoints.find((e: any) => e.url === "/api/auth/login" && e.method === "POST");
    expect(ep).toBeDefined();
    expect(ep.latency.p95).toBeLessThan(200);
  });

  it("all endpoints have < 5% error rate", () => {
    if (!api) return;
    for (const ep of api.endpoints) {
      const errorRate = ep.errorCount / ep.runs;
      expect(errorRate).toBeLessThan(0.05);
    }
  });
});

// ============================================================
// Electron Startup
// ============================================================
describe("Electron Startup", () => {
  let startup: any;

  beforeAll(() => {
    startup = loadJSON("electron-startup.json");
  });

  it("electron startup benchmark was run", () => {
    // This test is optional — not everyone builds standalone locally
    if (!startup) return;
    expect(startup.startupMs).not.toBeNull();
  });

  it("standalone server starts in under 5 seconds (P50)", () => {
    if (!startup?.startupMs) return;
    expect(startup.startupMs.p50).toBeLessThan(5000);
  });
});
